# Generated by Django 5.2.8 on 2025-11-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do tipo de item')),
                ('codigo_tipo', models.CharField(max_length=20, unique=True, verbose_name='Código do tipo')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes do item (tamanho, uso, observações gerais).', verbose_name='Descrição')),
            ],
        ),
    ]
