# Generated by Django 5.2.8 on 2025-11-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_exemplar', models.CharField(max_length=30, unique=True, verbose_name='Código do exemplar')),
                ('estado', models.CharField(choices=[('Bom', 'Bom'), ('Defeituoso', 'Defeituoso'), ('Em manutencao', 'Em manutenção')], default='Bom', max_length=20, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, help_text='Detalhes sobre este exemplar (marcas, defeitos, etc.).', verbose_name='Observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='core.item', verbose_name='Tipo de item')),
            ],
        ),
    ]
