# Generated by Django 5.2.8 on 2025-11-24 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exemplar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Data da reserva')),
                ('data_retirada', models.DateField(verbose_name='Data prevista para retirada')),
                ('data_devolucao', models.DateField(verbose_name='Data prevista para devolução')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelada', 'Cancelada'), ('Concluida', 'Concluída')], default='Pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Comentários sobre esta reserva (motivo, situação específica etc.).', verbose_name='Observações')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.item', verbose_name='Tipo de item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
