# Generated by Django 5.2.8 on 2025-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplar',
            name='estado',
        ),
        migrations.AddField(
            model_name='exemplar',
            name='condicao',
            field=models.CharField(choices=[('Bom', 'Bom'), ('Defeituoso', 'Defeituoso')], default='Bom', max_length=20, verbose_name='Condição'),
        ),
        migrations.AddField(
            model_name='exemplar',
            name='situacao',
            field=models.CharField(choices=[('Disponivel', 'Disponível'), ('Reservado', 'Reservado'), ('Em manutencao', 'Em manutenção')], default='Disponivel', max_length=20, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
