# Generated by Django 5.2.8 on 2025-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_exemplar_estado_exemplar_condicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
    ]
