# Generated by Django 5.2.8 on 2025-11-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuspAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nusp', models.CharField(max_length=20, unique=True, verbose_name='NUSP')),
            ],
        ),
    ]
