# Generated by Django 5.2.8 on 2025-11-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nuspautorizado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NuspAutorizado',
        ),
    ]
