# Generated by Django 5.2.8 on 2025-11-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_nuspautorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='exemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.exemplar'),
        ),
    ]
