# Generated by Django 5.2.8 on 2025-11-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora do cancelamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelamento_automatico',
            field=models.BooleanField(default=False, verbose_name='Cancelamento automático'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, help_text='Ex.: cancelada pelo aluno, não retirada em 24h, item indisponível, etc.', max_length=255, verbose_name='Motivo do cancelamento'),
        ),
        migrations.CreateModel(
            name='ReservaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora do evento')),
                ('acao', models.CharField(help_text='Ex.: criada, confirmada, retirada_confirmada, cancelada_automaticamente, concluida.', max_length=50, verbose_name='Ação')),
                ('mensagem', models.TextField(help_text='Descrição legível do que aconteceu nesta reserva.', verbose_name='Mensagem')),
                ('automatico', models.BooleanField(default=False, verbose_name='Ação automática')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(blank=True, help_text='Quem realizou a ação (deixe em branco para ações automáticas).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
