# Generated by Django 5.2.8 on 2025-11-28 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_reserva_cancelada_em_reserva_cancelamento_automatico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservahistorico',
            options={},
        ),
        migrations.RemoveField(
            model_name='reservahistorico',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='reservahistorico',
            name='automatico',
        ),
        migrations.RemoveField(
            model_name='reservahistorico',
            name='data',
        ),
        migrations.RemoveField(
            model_name='reservahistorico',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='reservahistorico',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reservahistorico',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_confirmou_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora que confirmou a devolução'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_confirmou_retirada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora que confirmou a retirada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_confirmou_devolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_confirmadas_devolucao', to=settings.AUTH_USER_MODEL, verbose_name='Quem confirmou a devolução'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_confirmou_retirada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_confirmadas_retirada', to=settings.AUTH_USER_MODEL, verbose_name='Quem confirmou a retirada'),
        ),
    ]
