# Generated by Django 5.2.8 on 2025-11-28 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_reservahistorico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario_cancelou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Quem cancelou'),
        ),
    ]
